app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),

    path('timetable', views.timetable, name='timetable'),
    path('add_timetable', views.add_timetable, name='add_timetable'),
    path('timetable/<int:timetable_id>/delete_timetable', views.delete_timetable, name='delete_timetable'),

    path('classes_journals', views.classes_journals, name='classes_journals'),
    path('add_mark', views.add_mark, name='add_mark'),

    path('add_class', views.add_class, name='add_class'),
    path('delete_class', views.delete_class, name='delete_class'),

    path('filter_pupils', views.filter_pupils, name='filter_pupils'),

    path('add_pupil', views.add_pupil, name='add_pupil'),
    path('delete_pupil', views.delete_pupil, name='delete_pupil'),

    path('filter_teachers', views.filter_teachers, name='filter_teachers'),
    path('add_teacher', views.add_teacher, name='add_teacher'),
    path('delete_teacher', views.delete_teacher, name='delete_teacher'),

    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('app.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/app/add_class.html
{% extends 'app/layout.html' %}

{% block title %}Add class{% endblock %}

{% block content %}
    <h2>Add class</h2>
    <form action="add_class" method="post">
        {% csrf_token %}
        <div class="row g-2 align-items-center mt-4">
            <div class="col-auto">
                <input type="text" class="form-control" name="new_class_name" placeholder="Class" required
                       aria-label="new_class_name">
            </div>

            <div class="col-auto">
                <button class="btn btn-primary" type="submit">Add</button>
            </div>
        </div>
    </form>

    <div class="mt-5">
        <b>Existing classes:
            {% for itm in classes %}
                ({{ itm.class_name }})
            {% endfor %}
        </b>
    </div>
{% endblock %}

templates/app/add_pupil.html
{% extends 'app/layout.html' %}

{% block title %}Add pupil{% endblock %}

{% block content %}
    <h2>Add pupil</h2>
    <form action="add_pupil" method="post">
        {% csrf_token %}
        <div class="row g-2 align-items-center mt-4">

            <div class="col-auto">
                <input type="text" class="form-control" name="first_name_pupil" placeholder="First name" required
                aria-label="first_name_pupil">
            </div>

            <div class="col-auto">
                <input type="text" class="form-control" name="second_name_pupil" placeholder="Second name" required
                aria-label="second_name_pupil">
            </div>

            <div class="col-auto">
                <select required class="form-select" name="pupil_class" aria-label="Choose class">
                    {% for itm in classes %}
                        <option value="{{ itm.class_name }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-auto">
                <button class="btn btn-primary" type="submit">Add</button>
            </div>

        </div>
    </form>
{% endblock %}

templates/app/add_timetable.html
{% extends 'app/layout.html' %}

{% block title %}Add timetable{% endblock %}

{% block content %}
    <h2>Add timetable</h2>
    <form action="add_timetable" method="POST">
        {% csrf_token %}
        <div class="row g-2 align-items-center mt-4">

            <div class="col-auto">
                <select required class="form-select" name="day" aria-label="Choose class">
                    <option value="Monday">Monday</option>
                    <option value="Tuesday">Tuesday</option>
                    <option value="Wednesday">Wednesday</option>
                    <option value="Thursday">Thursday</option>
                    <option value="Friday">Friday</option>
                </select>
            </div>

            <div class="col-auto">
                <select required class="form-select" name="time" aria-label="Choose class">
                    {% for itm in time %}
                    <option value="{{ forloop.counter0 }}">({{ forloop.counter }}) {{ itm }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-auto">
                <select required class="form-select" name="class_id" aria-label="Choose class">
                    {% for itm in classes %}
                        <option value="{{ itm.id }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-auto">
                <select required class="form-select" name="teacher_id" aria-label="Choose class">
                    {% for itm in teachers %}
                        <option value="{{ itm.id }}">({{ itm.teachers_class.class_name }}) {{ itm.second_name_teacher }} {{ itm.first_name_teacher }} - ({{ itm.teachers_lesson.lesson_name }})</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-auto">
                <button class="btn btn-primary" type="submit">Add</button>
            </div>

        </div>
    </form>

{% endblock %}

templates/app/classes_journals.html
{% extends 'app/layout.html' %}

{% block title %}Class Journal{% endblock %}

{% block content %}
    <h2 class="text-center">Class Journal</h2>
    <form action="classes_journals" method="POST" class="w-auto">
        {% csrf_token %}
        <div class="row justify-content-center mt-3">

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="pupils_class" aria-label="Choose class">
                    {% for itm in classes %}
                        <option value="{{ itm.class_name }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="pupils_lesson" aria-label="Choose day">
                    {% for itm in lessons %}
                        <option value="{{ itm.lesson_name }}">{{ itm.lesson_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </div>
    </form>

    {% if class %}
        <h4 class="text mt-5">{{ lesson.lesson_name }} ({{ class.class_name }})</h4>

        <div>

            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Date</th>
                    <th>Mark</th>
                </tr>
                </thead>

                <tbody>
                {% for itm in pupils %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ itm.pupil.second_name_pupil }}</td>
                        <td>{{ itm.pupil.first_name_pupil }}</td>
                        <td>{{ itm.date }}</td>
                        <td>{{ itm.mark }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>

    {% endif %}

{% endblock %}

templates/app/delete_class.html
{% extends 'app/layout.html' %}

{% block title %}Delete class{% endblock %}

{% block content %}
    <h2>Delete class</h2>
    <form action="delete_class" method="post">
        {% csrf_token %}

        <div class="row g-2 align-items-center mt-4">

            <div class="col-auto">
                <select required class="form-select" name="delete_class_name" aria-label="Choose class">
                    {% for itm in classes %}
                        <option value="{{ itm.class_name }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>

        </div>

    </form>

    <div class="mt-5">
        <b>Existing classes:
            {% for itm in classes %}
                ({{ itm.class_name }})
            {% endfor %}
        </b>
    </div>
{% endblock %}

templates/app/delete_pupil.html
{% extends 'app/layout.html' %}

{% block title %}Delete pupil{% endblock %}

{% block content %}
    <h2>Delete pupil</h2>
    <form action="delete_pupil" method="post">
        {% csrf_token %}

        <div class="row g-2 align-items-center mt-4">

            <div class="col-auto">
                <select required class="form-select" name="delete_pupil" aria-label="Choose class">
                    {% for itm in pupils %}
                        <option value="{{ itm.id }}">{{ itm.second_name_pupil }} {{ itm.first_name_pupil }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>

        </div>

    </form>
{% endblock %}

templates/app/delete_teacher.html
{% extends 'app/layout.html' %}

{% block title %}Delete teacher{% endblock %}

{% block content %}
    <h2>Delete teacher</h2>
    <form action="delete_teacher" method="post">
        {% csrf_token %}

        <div class="row g-2 align-items-center mt-4">

            <div class="col-auto">
                <select required class="form-select" name="teacher_id" aria-label="Choose class">
                    {% for itm in teachers %}
                        <option value="{{ itm.id }}">{{ itm.teachers_class.class_name }} {{ itm.second_name_teacher }} {{ itm.first_name_teacher }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>

        </div>

    </form>
{% endblock %}

templates/app/delete_timetable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DELETE</title>
</head>
<body>
DELETE
</body>
</html>

templates/app/filter_pupils.html
{% extends 'app/layout.html' %}

{% block title %}Pupils{% endblock %}

{% block content %}
    <h2 class="text-center">Pupils</h2>

    <form action="filter_pupils" method="POST">
        {% csrf_token %}

        <div class="row justify-content-center mt-3">

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="class_name" aria-label="Choose class">
                    <option value="All pupils">All pupils</option>
                    {% for itm in classes %}
                        <option value="{{ itm.class_name }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </div>

    </form>


    {% if pupils is not None %}
        <h4 class="text mt-5">{{ class_name }}</h4>

        <div>

            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>First name</th>
                    <th>Last name</th>
                    {% if class_name == 'All pupils' %}
                        <th>Class</th>
                    {% endif %}

                </tr>
                </thead>

                <tbody>
                {% for itm in pupils %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ itm.first_name_pupil }}</td>
                        <td>{{ itm.second_name_pupil }}</td>
                        {% if class_name == 'All pupils' %}
                            <td>{{ itm.current_class.class_name }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>

    {% endif %}

{% endblock %}

templates/app/filter_teachers.html
{% extends 'app/layout.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}
    <h2 class="text-center">Teachers</h2>
    <form action="filter_teachers" method="POST">
        {% csrf_token %}

        <div class="row justify-content-center mt-3">

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="class_id" aria-label="Choose class">
                    {#                        <option value="All teachers">All teachers</option>#}
                    {% for itm in classes %}
                        <option value="{{ itm.id }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </div>
    </form>


    {% if teachers is not None %}
        <h4 class="text mt-5">{{ teachers.0.teachers_class.class_name }}</h4>

        <div>

            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Second name</th>
                    <th>First name</th>
                    <th>Teachers lesson</th>
                </tr>
                </thead>

                <tbody>
                {% for itm in teachers %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ itm.first_name_teacher }}</td>
                        <td>{{ itm.second_name_teacher }}</td>
                        <td>{{ itm.teachers_lesson.lesson_name }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>

    {% endif %}

{% endblock %}

templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "app/css/layout.css" %}">
</head>
<body>

<!-- Side navigation -->
<div class="sidenav">
    <a href="{% url 'app:home' %}">Home</a>

    <a href="{% url 'app:add_class' %}">Add class</a>
    <a href="{% url 'app:delete_class' %}">Del class</a>

    <a href="{% url 'app:filter_pupils' %}">Pupils</a>
    <a href="{% url 'app:add_pupil' %}">Add pupil</a>
    <a href="{% url 'app:delete_pupil' %}">Del pupil</a>

    <a href="{% url 'app:filter_teachers' %}">Teachers</a>
    <a href="{% url 'app:add_teacher' %}">Add teacher</a>
    <a href="{% url 'app:delete_teacher' %}">Del teacher</a>

    <a href="{% url 'app:classes_journals' %}">Journals</a>
    <a href="{% url 'app:add_mark' %}">Add mark</a>

    <a href="{% url 'app:timetable' %}">Timetable</a>
    <a href="{% url 'app:add_timetable' %}">Add timetable</a>
</div>

<div class="container w-50 p-3">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

<!-- Page content -->
<div class="main">
    {% block content %}{% endblock %}
</div>

</body>
</html>

templates/app/login.html
{% extends 'app/layout.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    Login
{% endblock %}

templates/app/logout.html
{% extends 'app/layout.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    See you soon!
{% endblock %}

templates/app/timetable.html
{% extends 'app/layout.html' %}

{% block title %}Home page{% endblock %}

{% block content %}
    <h2 class="text-center">Timetable</h2>
    <form action="timetable" method="POST">
        {% csrf_token %}
        <div class="row justify-content-center mt-3">

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="class_name" aria-label="Choose class">
                    {% for itm in classes %}
                        <option value="{{ itm.class_name }}">{{ itm.class_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <select required class="form-select" name="day" aria-label="Choose day">
                    <option value="All weak">All week</option>
                    <option value="Monday">Monday</option>
                    <option value="Tuesday">Tuesday</option>
                    <option value="Wednesday">Wednesday</option>
                    <option value="Thursday">Thursday</option>
                    <option value="Friday">Friday</option>
                </select>
            </div>

            <div class="col-lg-2 col-sm-4">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </div>
    </form>

    {% if result is not None %}
        <div>
            <h4 class="text mt-5">{{ day }} ({{ class_name }})</h4>
            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    {% if day == 'All weak' %}
                        <th>Day</th>
                    {% endif %}
                    <th>Begin</th>
                    <th>End</th>
                    <th>Lesson</th>
                    <th>Teacher</th>
                    <th>Options</th>
                </tr>
                </thead>

                <tbody>
                {% for item in result %}
                    {% if item.day == 'Monday' %}
                        <tr class="table-active">
                    {% endif %}
                    {% if item.day == 'Tuesday' %}
                        <tr class="table-success">
                    {% endif %}
                    {% if item.day == 'Wednesday' %}
                        <tr class="table-primary">
                    {% endif %}
                    {% if item.day == 'Thursday' %}
                        <tr class="table-warning">
                    {% endif %}
                    {% if item.day == 'Friday' %}
                        <tr class="table-danger">
                    {% endif %}

                    <td>{{ forloop.counter }}</td>

                    {% if day == 'All weak' %}
                        <td>{{ item.day }}</td>
                    {% endif %}

                    <td>{{ item.time_begin }}</td>
                    <td>{{ item.time_end }}</td>
                    <td>{{ item.lesson.lesson_name }}</td>
                    <td>{{ item.teacher.second_name_teacher }} {{ item.teacher.first_name_teacher }}</td>
                    <td><a href="{% url 'app:delete_timetable' item.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    {% endif %}
{% endblock %}